// ─────────────────────────────────────────────
// Mock Data Store — Seeded for demonstration
// ─────────────────────────────────────────────

import type {
  Policy,
  GovernedSystem,
  AuditTrace,
  ImpactAssessment,
  HITLRequest,
  AppState,
  ProbeSession,
} from "../types";

function ts(daysAgo = 0, hoursAgo = 0): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  d.setHours(d.getHours() - hoursAgo);
  return d.toISOString();
}

// ── Policies ───────────────────────────────────

export const SEED_POLICIES: Policy[] = [
  // L3 Meta-Governance
  {
    id: "pol-l3-001",
    name: "Law 25 Omnibus Meta-Policy",
    description: "Top-level meta-governance rule ensuring all L2 policies remain aligned with Quebec Law 25 requirements. Reviewed quarterly.",
    level: "L3_META",
    status: "ACTIVE",
    parentId: null,
    childIds: ["pol-l2-001", "pol-l2-002", "pol-l2-003"],
    rule: "All L2 policies governing systems that process personal information of Quebec residents MUST map to at least one active Law 25 section. Any L2 policy without a Law 25 anchor is flagged for review within 24h.",
    invariant: "Governance of governance must itself be governed; a meta-policy that cannot audit its own children is a boundary marker, not a framework.",
    riskLevel: "HIGH",
    createdAt: ts(90),
    updatedAt: ts(3),
    executionCount: 42,
    lastExecutedAt: ts(0, 2),
    law25Linked: true,
    law25Section: "18.1",
  },
  {
    id: "pol-l3-002",
    name: "Recursive Depth Governance",
    description: "Meta-policy preventing policy loops and infinite recursion in the policy tree.",
    level: "L3_META",
    status: "ACTIVE",
    parentId: null,
    childIds: ["pol-l2-004"],
    rule: "No policy may reference itself as a parent. Policy chains must terminate within 5 levels. Recursion invariant must be named in any chain > 3 levels deep.",
    invariant: "Inclusion gives recursion material; recursion gives inclusion motion; governance prevents the loop from mistaking repetition for depth.",
    riskLevel: "MEDIUM",
    createdAt: ts(60),
    updatedAt: ts(7),
    executionCount: 18,
    lastExecutedAt: ts(1),
    law25Linked: false,
  },

  // L2 Policies
  {
    id: "pol-l2-001",
    name: "Automated Decision Transparency",
    description: "Governs all systems making automated decisions affecting individuals. Enforces Section 12.1 disclosure requirements.",
    level: "L2_POLICY",
    status: "ACTIVE",
    parentId: "pol-l3-001",
    childIds: ["pol-l1-001", "pol-l1-002", "pol-l1-005"],
    rule: "Any system performing automated decisions must: (1) generate a Section 12.1 transparency notice, (2) configure HITL queue, (3) log every decision in the audit trace. Non-compliant systems are suspended within 48h.",
    riskLevel: "HIGH",
    createdAt: ts(75),
    updatedAt: ts(5),
    executionCount: 156,
    lastExecutedAt: ts(0, 1),
    law25Linked: true,
    law25Section: "12.1",
  },
  {
    id: "pol-l2-002",
    name: "Consent Lifecycle Management",
    description: "Governs collection, storage, and withdrawal of personal data consent.",
    level: "L2_POLICY",
    status: "ACTIVE",
    parentId: "pol-l3-001",
    childIds: ["pol-l1-003"],
    rule: "Consent must be explicitly obtained before personal data collection. Consent withdrawal must be honored within 72h. Consent records retained for audit purposes per Law 25 s.8.",
    riskLevel: "HIGH",
    createdAt: ts(70),
    updatedAt: ts(10),
    executionCount: 89,
    lastExecutedAt: ts(0, 4),
    law25Linked: true,
    law25Section: "8",
  },
  {
    id: "pol-l2-003",
    name: "Incident Response & Breach Notification",
    description: "72-hour notification requirement under Law 25 s.17.",
    level: "L2_POLICY",
    status: "ACTIVE",
    parentId: "pol-l3-001",
    childIds: ["pol-l1-004"],
    rule: "On detection of a privacy incident affecting personal information: notify CAI within 72h, notify affected individuals without undue delay, create incident report in audit log. Severity classification: LOW/MEDIUM/HIGH/CRITICAL.",
    riskLevel: "CRITICAL",
    createdAt: ts(65),
    updatedAt: ts(2),
    executionCount: 7,
    lastExecutedAt: ts(14),
    law25Linked: true,
    law25Section: "17",
  },
  {
    id: "pol-l2-004",
    name: "Third-Party Data Processing",
    description: "Governs all data processing agreements with external vendors.",
    level: "L2_POLICY",
    status: "DRAFT",
    parentId: "pol-l3-002",
    childIds: [],
    rule: "All third-party processors must: sign a data processing agreement, maintain equivalent privacy standards, be listed in the data inventory, be subject to annual audit. DRAFT — pending legal review.",
    riskLevel: "HIGH",
    createdAt: ts(10),
    updatedAt: ts(1),
    executionCount: 0,
    lastExecutedAt: null,
    law25Linked: true,
    law25Section: "21",
  },

  // L1 Scripts
  {
    id: "pol-l1-001",
    name: "Max Token Limit Enforcer",
    description: "Technical constraint: no single AI request may process more than 8,192 tokens of personal data.",
    level: "L1_SCRIPT",
    status: "ACTIVE",
    parentId: "pol-l2-001",
    childIds: [],
    rule: "ASSERT: request.tokens <= 8192 WHERE request.contains_personal_data == true. REJECT with audit log entry if exceeded.",
    riskLevel: "MEDIUM",
    createdAt: ts(60),
    updatedAt: ts(20),
    executionCount: 4521,
    lastExecutedAt: ts(0, 0),
    law25Linked: false,
  },
  {
    id: "pol-l1-002",
    name: "No Personal Data Extraction",
    description: "Technical guardrail preventing raw personal data from appearing in AI model outputs.",
    level: "L1_SCRIPT",
    status: "ACTIVE",
    parentId: "pol-l2-001",
    childIds: [],
    rule: "SCAN output for: SIN, health card numbers, date of birth + name combos, full address + name combos. REDACT or REJECT if found. Log incident.",
    riskLevel: "CRITICAL",
    createdAt: ts(60),
    updatedAt: ts(15),
    executionCount: 4521,
    lastExecutedAt: ts(0, 0),
    law25Linked: true,
    law25Section: "8",
  },
  {
    id: "pol-l1-003",
    name: "Consent Token Validator",
    description: "Validates consent tokens before any data processing operation.",
    level: "L1_SCRIPT",
    status: "ACTIVE",
    parentId: "pol-l2-002",
    childIds: [],
    rule: "REQUIRE valid consent_token WHERE operation.processes_personal_data == true. Token must be: non-expired, not withdrawn, scope-matched. BLOCK operation if validation fails.",
    riskLevel: "HIGH",
    createdAt: ts(55),
    updatedAt: ts(12),
    executionCount: 3210,
    lastExecutedAt: ts(0, 1),
    law25Linked: true,
    law25Section: "8",
  },
  {
    id: "pol-l1-004",
    name: "Breach Detection Sentinel",
    description: "Automated detection of potential privacy incidents.",
    level: "L1_SCRIPT",
    status: "ACTIVE",
    parentId: "pol-l2-003",
    childIds: [],
    rule: "MONITOR: unauthorized access attempts, bulk data exports, anomalous query patterns. THRESHOLD: >100 records/min triggers HIGH alert. AUTO-ESCALATE to HITL queue. Log all events.",
    riskLevel: "CRITICAL",
    createdAt: ts(50),
    updatedAt: ts(3),
    executionCount: 18042,
    lastExecutedAt: ts(0, 0),
    law25Linked: true,
    law25Section: "17",
  },
  {
    id: "pol-l1-005",
    name: "Audit L1 Scripts (24h Cycle)",
    description: "Periodic integrity check of all active L1 scripts.",
    level: "L1_SCRIPT",
    status: "SUSPENDED",
    parentId: "pol-l2-001",
    childIds: [],
    rule: "EVERY 24h: verify L1 script checksums, confirm execution logs match expected counts, flag any script with >3 consecutive failures. SUSPENDED pending hash verification update.",
    riskLevel: "MEDIUM",
    createdAt: ts(40),
    updatedAt: ts(0),
    executionCount: 12,
    lastExecutedAt: ts(2),
    law25Linked: false,
  },
];

// ── Governed Systems ───────────────────────────

export const SEED_SYSTEMS: GovernedSystem[] = [
  {
    id: "sys-001",
    name: "PHAROS Decision Engine",
    description: "AI-powered governance evaluation system with automated adjudication capabilities.",
    riskLevel: "HIGH",
    status: "ACTIVE",
    assignedPolicies: ["pol-l2-001", "pol-l1-001", "pol-l1-002", "pol-l3-001"],
    lastAuditAt: ts(1),
    complianceScore: 82,
    createdAt: ts(90),
  },
  {
    id: "sys-002",
    name: "Consent Management Portal",
    description: "Customer-facing portal for personal data consent collection and management.",
    riskLevel: "HIGH",
    status: "ACTIVE",
    assignedPolicies: ["pol-l2-002", "pol-l1-003"],
    lastAuditAt: ts(3),
    complianceScore: 91,
    createdAt: ts(80),
  },
  {
    id: "sys-003",
    name: "HR Analytics Platform",
    description: "Internal HR tool with automated employee risk scoring and performance analysis.",
    riskLevel: "CRITICAL",
    status: "ACTIVE",
    assignedPolicies: ["pol-l2-001", "pol-l1-002", "pol-l1-004"],
    lastAuditAt: ts(7),
    complianceScore: 64,
    createdAt: ts(120),
  },
  {
    id: "sys-004",
    name: "External Data Broker Feed",
    description: "Third-party data enrichment service for customer profiles.",
    riskLevel: "CRITICAL",
    status: "PAUSED",
    assignedPolicies: ["pol-l2-004"],
    lastAuditAt: ts(30),
    complianceScore: 31,
    createdAt: ts(200),
  },
];

// ── Audit Traces ───────────────────────────────

export const SEED_AUDITS: AuditTrace[] = [
  {
    id: "aud-001",
    policyId: "pol-l2-001",
    policyName: "Automated Decision Transparency",
    systemId: "sys-001",
    systemName: "PHAROS Decision Engine",
    verdict: "PASS",
    timestamp: ts(0, 2),
    durationMs: 1840,
    repeatedBlocks: 1,
    compressionRatio: 0.92,
    invariantNamed: false,
    governorAction: "CONTINUE_WITH_GOVERNOR",
    ruling: null,
    transcript: "Policy evaluation passed. Section 12.1 notice on file. HITL queue active.",
    hedgesRemoved: 0,
    law25Relevant: true,
  },
  {
    id: "aud-002",
    policyId: "pol-l1-002",
    policyName: "No Personal Data Extraction",
    systemId: "sys-003",
    systemName: "HR Analytics Platform",
    verdict: "WARN",
    timestamp: ts(0, 5),
    durationMs: 420,
    repeatedBlocks: 0,
    compressionRatio: 1.0,
    invariantNamed: false,
    governorAction: null,
    ruling: null,
    transcript: "Output scan detected potential date-of-birth pattern. Redacted. No SIN or health card found.",
    hedgesRemoved: 2,
    law25Relevant: true,
  },
  {
    id: "aud-003",
    policyId: "pol-l3-001",
    policyName: "Law 25 Omnibus Meta-Policy",
    systemId: "sys-004",
    systemName: "External Data Broker Feed",
    verdict: "FAIL",
    timestamp: ts(1),
    durationMs: 3210,
    repeatedBlocks: 4,
    compressionRatio: 0.71,
    invariantNamed: true,
    governorAction: "TERMINATE_RECURSION",
    ruling: "Inclusion gives recursion material; recursion gives inclusion motion; governance prevents the loop from mistaking repetition for depth.",
    transcript: "System paused. Third-party data processing policy in DRAFT. No valid s.21 consent framework in place.",
    hedgesRemoved: 0,
    law25Relevant: true,
  },
  {
    id: "aud-004",
    policyId: "pol-l1-004",
    policyName: "Breach Detection Sentinel",
    systemId: "sys-002",
    systemName: "Consent Management Portal",
    verdict: "PASS",
    timestamp: ts(2),
    durationMs: 88,
    repeatedBlocks: 0,
    compressionRatio: 1.0,
    invariantNamed: false,
    governorAction: null,
    ruling: null,
    transcript: "24h monitoring cycle: no anomalies detected. Query rates nominal. Bulk export: none.",
    hedgesRemoved: 0,
    law25Relevant: false,
  },
  {
    id: "aud-005",
    policyId: "pol-l2-003",
    policyName: "Incident Response & Breach Notification",
    systemId: "sys-003",
    systemName: "HR Analytics Platform",
    verdict: "WARN",
    timestamp: ts(5),
    durationMs: 2100,
    repeatedBlocks: 2,
    compressionRatio: 0.85,
    invariantNamed: false,
    governorAction: "CONTINUE_WITH_GOVERNOR",
    ruling: null,
    transcript: "Incident response procedure tested. 72h notification clock: verified. CAI contact list: outdated — flagged for update.",
    hedgesRemoved: 1,
    law25Relevant: true,
  },
];

// ── Impact Assessments ─────────────────────────

export const SEED_ASSESSMENTS: ImpactAssessment[] = [
  {
    id: "pia-001",
    systemId: "sys-001",
    systemName: "PHAROS Decision Engine",
    status: "COMPLETE",
    createdAt: ts(45),
    completedAt: ts(30),
    transparencyDisclosed: true,
    humanOversightEnabled: true,
    dataCategoriesProcessed: [
      "Identity data (name, ID)",
      "Behavioral data (query patterns)",
      "Risk scores (derived)",
    ],
    retentionPeriodDays: 365,
    thirdPartySharing: false,
    automaticDecisionMaking: true,
    section12_1Notice: "Generated — on file",
    lastReviewedBy: "Privacy Officer",
    riskScore: 45,
    findings: [
      "Derived risk scores may constitute sensitive information under Law 25",
      "Audit log retention adequate",
    ],
    mitigations: [
      "Risk scores anonymized before logging",
      "HITL queue configured for high-risk decisions",
    ],
  },
  {
    id: "pia-002",
    systemId: "sys-003",
    systemName: "HR Analytics Platform",
    status: "IN_PROGRESS",
    createdAt: ts(14),
    completedAt: null,
    transparencyDisclosed: false,
    humanOversightEnabled: true,
    dataCategoriesProcessed: [
      "Employment history",
      "Performance metrics",
      "Health-related leave data",
      "Biometric data (access control)",
    ],
    retentionPeriodDays: 730,
    thirdPartySharing: true,
    automaticDecisionMaking: true,
    section12_1Notice: null,
    lastReviewedBy: null,
    riskScore: 78,
    findings: [
      "Health-related leave data is sensitive — requires explicit consent under s.8.1",
      "Automated performance scoring may trigger s.12.1 disclosure",
      "Third-party HR vendor lacks verified Law 25 compliance",
    ],
    mitigations: [
      "Pending: obtain explicit consent for health data processing",
      "Pending: generate s.12.1 notice",
    ],
  },
  {
    id: "pia-003",
    systemId: "sys-004",
    systemName: "External Data Broker Feed",
    status: "NOT_STARTED",
    createdAt: ts(7),
    completedAt: null,
    transparencyDisclosed: false,
    humanOversightEnabled: false,
    dataCategoriesProcessed: [
      "Contact data",
      "Inferred demographics",
      "Purchase history (third-party)",
    ],
    retentionPeriodDays: 0,
    thirdPartySharing: true,
    automaticDecisionMaking: false,
    section12_1Notice: null,
    lastReviewedBy: null,
    riskScore: 91,
    findings: [],
    mitigations: [],
  },
];

// ── HITL Queue ─────────────────────────────────

export const SEED_HITL: HITLRequest[] = [
  {
    id: "hitl-001",
    requestedAt: ts(0, 3),
    requestedBy: "SUB-8842-QC",
    systemId: "sys-001",
    systemName: "PHAROS Decision Engine",
    decisionSummary: "Automated governance risk score of HIGH assigned to vendor integration request #4421. Requesting human review of scoring methodology.",
    status: "PENDING",
    assignedTo: null,
    resolvedAt: null,
    resolution: null,
    law25Right: "EXPLANATION",
    urgency: "NORMAL",
  },
  {
    id: "hitl-002",
    requestedAt: ts(1),
    requestedBy: "SUB-0291-QC",
    systemId: "sys-003",
    systemName: "HR Analytics Platform",
    decisionSummary: "Automated performance review flagged employee file for termination consideration. Requesting mandatory human review per Law 25 s.12.1.",
    status: "ASSIGNED",
    assignedTo: "HR Compliance Officer",
    resolvedAt: null,
    resolution: null,
    law25Right: "REVIEW",
    urgency: "URGENT",
  },
  {
    id: "hitl-003",
    requestedAt: ts(3),
    requestedBy: "SUB-5517-QC",
    systemId: "sys-003",
    systemName: "HR Analytics Platform",
    decisionSummary: "Subject requests correction to health leave data that incorrectly influenced risk score.",
    status: "RESOLVED",
    assignedTo: "Data Protection Officer",
    resolvedAt: ts(1),
    resolution: "Record corrected. Risk score recalculated. New score: MEDIUM. Notification sent to subject.",
    law25Right: "CORRECTION",
    urgency: "NORMAL",
  },
  {
    id: "hitl-004",
    requestedAt: ts(0, 1),
    requestedBy: "SUB-3309-QC",
    systemId: "sys-001",
    systemName: "PHAROS Decision Engine",
    decisionSummary: "Policy engine rejected compliance certification request with no human override option presented. Subject objects to automated rejection.",
    status: "ESCALATED",
    assignedTo: "Legal Counsel",
    resolvedAt: null,
    resolution: null,
    law25Right: "OBJECTION",
    urgency: "CRITICAL",
  },
];

// ── Initial App State ──────────────────────────

const blankProbeSession: ProbeSession = {
  id: "probe-new",
  provider: "anthropic",
  model: "claude-sonnet-4-20250514",
  topic: "",
  language: "en",
  phase: "IDLE",
  messages: [],
  pipeline: [],
  currentStep: 0,
  governorStats: {
    repeatedBlocks: 0,
    compressionRatio: 1,
    invariantNamed: false,
    action: null,
    ruling: "",
  },
  startedAt: null,
  completedAt: null,
  error: null,
};

export const INITIAL_STATE: AppState = {
  route: "dashboard",
  policies: SEED_POLICIES,
  systems: SEED_SYSTEMS,
  auditTraces: SEED_AUDITS,
  assessments: SEED_ASSESSMENTS,
  hitlQueue: SEED_HITL,
  probeSession: blankProbeSession,
};

export const BLANK_PROBE_SESSION = blankProbeSession;